#!/bin/bash

PROP_FILE="/opt/semosshome/RDF_Map.prop"

# List all the relevant environment variable names as they appear in property file

VARS=(
    ADMIN_ONLY_PROJECT_ADD
    ADMIN_ONLY_PROJECT_DELETE
    ADMIN_ONLY_PROJECT_ADD_ACCESS
    ADMIN_ONLY_PROJECT_SET_PUBLIC
    ADMIN_ONLY_PROJECT_SET_DISCOVERABLE
    ADMIN_ONLY_INSIGHT_SET_PUBLIC
    ADMIN_ONLY_INSIGHT_ADD_ACCESS
    ADMIN_ONLY_INSIGHT_SHARE
    ADMIN_ONLY_DB_ADD
    ADMIN_ONLY_DB_DELETE
    ADMIN_ONLY_DB_ADD_ACCESS
    ADMIN_ONLY_DB_SET_PUBLIC
    ADMIN_ONLY_DB_SET_DISCOVERABLE
    ADMIN_ONLY_MODEL_ADD
    ADMIN_ONLY_MODEL_DELETE
    ADMIN_ONLY_MODEL_ADD_ACCESS
    ADMIN_ONLY_MODEL_SET_PUBLIC
    ADMIN_ONLY_MODEL_SET_DISCOVERABLE
    ADMIN_ONLY_STORAGE_ADD
    ADMIN_ONLY_STORAGE_DELETE
    ADMIN_ONLY_STORAGE_ADD_ACCESS
    ADMIN_ONLY_STORAGE_SET_PUBLIC
    ADMIN_ONLY_STORAGE_SET_DISCOVERABLE
    ADMIN_ONLY_VECTOR_ADD
    ADMIN_ONLY_VECTOR_DELETE
    ADMIN_ONLY_VECTOR_ADD_ACCESS
    ADMIN_ONLY_VECTOR_SET_PUBLIC
    ADMIN_ONLY_VECTOR_SET_DISCOVERABLE
    ADMIN_ONLY_FUNCTION_ADD
    ADMIN_ONLY_FUNCTION_DELETE
    ADMIN_ONLY_FUNCTION_ADD_ACCESS
    ADMIN_ONLY_FUNCTION_SET_PUBLIC
    ADMIN_ONLY_FUNCTION_SET_DISCOVERABLE
    ADMIN_ONLY_VIEW_MENU_BAR
    ADMIN_ONLY_NON_APPROVED_PROD_ITEM
)

# if [[ -z $ADMIN_ONLY_FUNCTION_ADD ]]; then
# echo "No admin only function add flag"
# else sed -i "s@ADMIN_ONLY_FUNCTION_ADD.*@ADMIN_ONLY_FUNCTION_ADD\t$ADMIN_ONLY_FUNCTION_ADD@g" /opt/semosshome/RDF_Map.prop
# fi

for VAR in "${VARS[@]}"; do
  VALUE="${!VAR}"
  if [[ -z $VALUE ]]; then
    echo "No ${VAR,,//_/ } flag"   # Lowercase varname, replace _ with space for readable messages
  else
    sed -i "s@^${VAR}.*@${VAR}\t${VALUE}@g" "$PROP_FILE"
  fi
done